### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by flhuihui1001** [gwsb-istm-6212-fall-2016/AidaRoxas#1]
Hi Aida,

I am able to download your code and run it on the datanotebook.org. I have some troubles to read the file on gutenberg, but I changed the link and then read the file and run your code. I can totaly reduplicate your results on my computer. And I appreciate you wrote detailed comments on every step so that I can read your codes. Good job!

Here are some specifi comments:

Problem 1 

part A: I can run your code but we get different results.  Your number is smaller than mine. Firstly I though you may make some mistakes. You did not  use  '\w{{2,}}' to split every word to a separate line. So actually  we are counting the number of lines that include those names. In this way, we count a line once where names appear multiple times, thus missing many times. After reading your comments, you actually consider the difference between 'Jo' and 'Joanna'. I did not think about that. This is inspiring. I am not sure which way is better, but definitely you give me some new insights.

part B: precise and concise code. Good job!

Problem 2: same results. I like your cvs look. A chart would be more readable than pure text.

Problem 3: Codes are good and we get the  same results. but we made the same mistake. The assignment asks us to write separate little programs to replace our codes. However, we just put the codes directly in the ipynb. Besides, the answers for the last 2 questions are missing.

In general, this project finished most of the requirements. It's good. At the same, it needs some improvement. 

Regards,
Livia

**Comment by roxa12** [comment]
Thank you. I was hoping you noticed that I created a folder that will be deleted at the end to clean up any computer that would run this program. I enjoyed this exercise and agree with you that I am a little unsure of my answers.

Best,
Aida
