### ISSUE TITLE
Review of Project-01 by Divya

### ISSUE THREAD

**Issue by divyagorwara** [gwsb-istm-6212-fall-2016/AidaRoxas#2]
**Hey Aida,**

When I downloaded your notebook and ran it, it gave me few errors. Your !wget command is not able to extract the file properly. So, I ran your code in another notebook, unfortunately we are not getting the same results. Your code for problem-1 part 1 is counting the number of matching lines instead of the number of words. For problem-1 part 2 the code is perfect, but again I cannot run it in your notebook. 

In problem 2, you did very well. All your codes run smoothly and produce correct output. I liked that you used csvlook for making your output look more sophisticated. You also used csvstat for the verification, that was wise.

Since, you did not attempt problem 3, I have nothing to comment on that. Overall you did a good job. The explanations before every code makes your project pretty easy to understand.

**Goodluck
Divya**

**Comment by roxa12** [comment]
Thank you Divya. I hoped you liked the folder creation that would delete the files downloaded after the program. I was having problems doing wget from github so I re-routed to Gutenburg files. Over-all, I did not have time to finish this. We all had a killer week! :) But I appreciate your comment.
Aida
