### ISSUE TITLE
Review on project2

### ISSUE THREAD

**Issue by yang127** [gwsb-istm-6212-fall-2016/AidaRoxas#3]
Hi Aida,

Great job on completing project 2, I was able to execute the file on datanotebook.org and the outcome looks good. 

For Part 1, I think you did a good job using markdown cells and following the professor's requirements. The queries are simple and that would how I approach Part 1 as well. One thing is that for ARREST_TIME it stands for the date and time that criminer get arrested and I think your description can be a little more accurate. 
 
For Part 2, the queries are well structured and the markdown cells did a good job as well. I see you utilized a lot of histograms, which is good as it give a better idea of your targeted question and it's easier to understand. In addition, I like how to update your null values. Just a suggestion, I think you can apply the timestamp process, which will be helpful for your future analysis if it is time related. 

For Part 3, I think you did a good job, I only have problem execute the second to last query. And I like how you create sample output for your dimension tables so you can test run your queries. 

For Part 4, I like your overall queries and I think you are trying to analyze the same questions you analyze in Part 2. One thing is I think getting the top 10 Central Control Record number is not a good predictor as I'm a little confused what you are going to analyze here. And it's really a coincidence you also mentioned the relationship of crimes and summer temperature just like we had. 

I like your answer on the bonus!

Overall, good job.

Yi

**Comment by roxa12** [comment]
Hi Yi,
Thank you for your feedback. :)

-Aida
