### ISSUE TITLE
Review on Project 2

### ISSUE THREAD

**Issue by xinyicoco** [gwsb-istm-6212-fall-2016/AidaRoxas#4]
Hi Aida,
Great job! Here is my review for your Project 02.

I can download and run your jupyter notebook quite well. I can see that you have given output for each of the four problems in very clear format. You have chosen “Pittsburgh Crime” csv file which includes a lot of interesting attributes.

For Problem#1, You have clearly identified your attributes and find out the null values. 

For Problem #2, you have demonstrated your skills of exploring your data using sql. You have successfully identified the top 10 types of crimes happened and the top 10 dangerous neighborhoods. You also identified the month and year with the most crime happened.  

For Problem #3, you have identified two dimensions, one is description dimension and the other one is location dimension. For each of the dimension, you have created a serial primary key. You also inserted the primary keys from the two dimension tables to the fact table.

For Problem#4, you explored the new schema and find out the top 10 type of crime and top 10 dangerous locations, which match the results from problem 2. You have demonstrated you skills of joining two tables by using foreign keys.

For the bonus question, you have discussed your methodology of automating data. Good job completing Project 2!

Thanks,
Xinyi

**Comment by roxa12** [comment]
Thank you Xinyi,

I appreciate the feedback.

Aida
