### ISSUE TITLE
Review on Project 2

### ISSUE THREAD

**Issue by shiyoudan** [gwsb-istm-6212-fall-2016/AidaRoxas#5]
Hi dear Aida!

I feel very happy to review your project! I can run your code except the code of diagram about star schema: Image(filename = PATH + "table.png", width=1000, height=1000). Which means I cannot reproduce the diagram about star schema. Other code is fine and frequently execute!

Problem 1, everything is good, I can clearly see that the information of each column.

Problem 2, your results shows me a overview of criminal, which is different from my topic. Mostly, I like your method about showing a overview of the column name, data type, max character length and if it is nullable. I type these information by words, which is not smart.

Problem 3, your fact table is good, and those two dimension table also correctly connect with fact table.  I also use location table and description table in my project, besides, I also have a time dimension table table connected with fact table. 

Problem 4, your results give me many inspirations! I also finish some count processing in my project. But I didn't realize that I can draw a pie chart to show something when I do my project! I'll use these good idea to explore some problem next time!

All in all, good job! And thanks for your pie chart idea!

Regards,
Youdan

**Comment by shiyoudan** [comment]
Oh I found your .png!! I'm so so sorry!!

**Comment by roxa12** [comment]
Hi Youdan,

Thank you for looking into our group's work. I appreciate your comments.

Best,
Aida
