### ISSUE TITLE
Project 2 Review

### ISSUE THREAD

**Issue by LingyaoMeng** [gwsb-istm-6212-fall-2016/AidaRoxas#6]
Hi Aida!

Great job overall! Everything runs smoothly except the star schema graph, I wish you have zipped it together with the python notebook:) or put them together in a separate folder. I love how well you documented the whole file in markdown cells and the format is wonderful and easy to spot. 

You guys went through great length in part two to explore the data. It's very refreshing to see that much information you guys gathered before star schema. However, I would love it more if you guys can present a small portion of the data just to give an overview. For example, the first ten rows of data like you did for part 4. 

Lingyao

**Comment by roxa12** [comment]
Thanks for your comments Lingyao. This helps!
